---
framework: jest
postMerge:
  pattern:
    - './tests/**/*.test.js'
preMerge:
  pattern:
    - './tests/**/*.test.js'
preRun:
  command:
    - npm ci
postRun:
  command:
    - node --version
version: 2.0
